#server:
#  port: 8080
#  ssl:
#    enabled: true
#    key-store: classpath:javatechie.jks
#    key-store-password: password
#    key-password: password
#    key-alias: spring-https    
aes:
  encryption:
    key: this-is-test-key
spring:
  main:
    allow-bean-definition-overriding: true  
  datasource:
    url: jdbc:mysql://database-1.cn86imikwaj5.ap-south-1.rds.amazonaws.com:3306/orivehrm
    username: oriveadmin
    password: orivedb2628
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: SEURITY-SERVICE   
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: hr.orivesolutions@gmail.com
    password: ieyh njde yroo ebij
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
           
    smtp:
      connectiontimeout: 5000
      timeout: 5000
      writetimeout: 5000
      auth: true
      starttls:
        enable: true
      ssl:
        enable: false
    debug: true
    
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
logging:
  level:
    org:
      springframework:
        security: DEBUG
        
        
       
